services:
  next:
    build:
      context: .
      target: dev
    command: sh -c 'pnpm install && pnpm run dev'
    volumes:
      - ./:/code
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    environment:
      - PORT=${PORT:-3000}
    env_file:
      - .env
